### ISSUE TITLE
Prepare initial release 1.0.0

### ISSUE THREAD

**Issue by lrapetti** [robotology/wearables#73]
Given that the code contained in `Wearable` can be considered being stable for a while, and given the discussion in https://github.com/robotology/robotology-superbuild/issues/331, I think we might do an initial release (v.1.0, v.0.1 ????) with the current version of the code.

@Yeshasvitvs @diegoferigo @traversaro what do you think?

**Comment by traversaro** [comment]
I agree.

**Comment by diegoferigo** [comment]
I would suggest following [semantic versioning](https://semver.org/) as much as possible. Since Wearable uses quite extensive interfaces, if we have pending modifications of the headers we should do them before the release.

We are using the project already for more than one year, and right now it's fairly stable. I would agree to release the first stable version `1.0` and freeze the APIs.

**Comment by lrapetti** [comment]
Initial Release can be found at https://github.com/robotology/wearables/releases/tag/v1.0.0
